# -*- coding: utf-8 -*-
"""decisiontree_kaggledataset.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zqtob0Emt0I59biDveEcAT9Q3duBEuPL
"""

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

df = pd.read_csv("Iris.csv")

print(df.head())

X = df[['SepalLengthCm', 'SepalWidthCm',
        'PetalLengthCm', 'PetalWidthCm']]

y = df[['Species']]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

m = DecisionTreeClassifier()

m.fit(X_train, y_train)

y_pred = m.predict(X_test)

print("Classification Report: ", classification_report(y_test, y_pred))

a = [[5.1,3.5,1.4,0.2]]

p = m.predict(a)

print(p)