# -*- coding: utf-8 -*-
"""DecisionTree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ecRPLi606lv20pltdpUN24Zh7QkX90Es
"""

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

data = {'Study_Hours': [1,2,3,4,5,6,7,8,9,10,2,4,6,8,10],
        'Attendence' : [50,55,60,65,70,75,80,85,90,95,52,68,78,88,98],
        'Internal_Marks' : [30,35,40,45,50,55,60,65,70,85,32,48,58,78,90],
        'Performance' : ['low','low','low','average','average','average','excellent','excellent','excellent','average','gud','gud','average', 'average','excellent']}

df=pd.DataFrame(data)
print(df)

X = df[['Study_Hours','Attendence','Internal_Marks']]

y = df['Performance']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

m = DecisionTreeClassifier()

m.fit(X_train, y_train)

y_pred = m.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

print("Classification Report:", classification_report(y_test, y_pred))

print("Confusion Matrix:", confusion_matrix(y_test, y_pred))

a = [[5,77,68]]

a = int(input("Enter Study Hours: "))
b = int(input("Enter Attendence: "))
c = int(input("Enter Internal Marks: "))
a = np.array([[a,b,c]])

p = m.predict(a)

print(p)