# -*- coding: utf-8 -*-
"""Image_pred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p7uOwgVd-8ibND4hBnNPgKJwWhlDQTsm
"""

import os
import zipfile
import numpy as np
import matplotlib.pyplot as plt

from PIL import Image

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

from google.colab import files

uploaded = files.upload()

zip_file = next(name for name in uploaded.keys() if name.endswith(".zip"))

with zipfile.ZipFile(zip_file, "r") as zip_ref:
    zip_ref.extractall("/content/apple_tomato")

print("Dataset extracted successfully!")

for root, dirs, files_list in os.walk("/content/apple_tomato"):
    print(root)
    print("Folders:", dirs)
    print("Files:", len(files_list))
    print()

apple_path = "/content/apple_tomato/train/apples"
tomato_path = "/content/apple_tomato/train/tomatoes"

print("Apple images:", len(os.listdir(apple_path)))
print("Tomato images:", len(os.listdir(tomato_path)))

apple_image = os.listdir(apple_path)[0]
tomato_image = os.listdir(tomato_path)[0]

apple_img = Image.open(os.path.join(apple_path, apple_image))
tomato_img = Image.open(os.path.join(tomato_path, tomato_image))

plt.figure(figsize=(8, 4))

plt.subplot(1, 2, 1)
plt.imshow(apple_img)
plt.title("Apple")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(tomato_img)
plt.title("Tomato")
plt.axis("off")

plt.show()

IMG_SIZE = 64

X = []
y = []

# Apple = 0
for filename in os.listdir(apple_path):
    try:
        img_path = os.path.join(apple_path, filename)

        img = Image.open(img_path).convert("RGB")
        img = img.resize((IMG_SIZE, IMG_SIZE))

        img_array = np.array(img)

        X.append(img_array.flatten())
        y.append(0)

    except:
        pass


# Tomato = 1
for filename in os.listdir(tomato_path):
    try:
        img_path = os.path.join(tomato_path, filename)

        img = Image.open(img_path).convert("RGB")
        img = img.resize((IMG_SIZE, IMG_SIZE))

        img_array = np.array(img)

        X.append(img_array.flatten())
        y.append(1)

    except:
        pass


X = np.array(X)
y = np.array(y)

print("X shape:", X.shape)
print("y shape:", y.shape)

X = X / 255.0

print("Minimum pixel value:", X.min())
print("Maximum pixel value:", X.max())

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

model = LogisticRegression(
    max_iter=1000
)

model.fit(X_train, y_train)

print("Model training completed!")

y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print("Accuracy percentage:", accuracy * 100, "%")

cm = confusion_matrix(y_test, y_pred)

print(cm)

plt.figure(figsize=(5, 4))

plt.imshow(cm)

plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.xticks([0, 1], ["Apple", "Tomato"])
plt.yticks([0, 1], ["Apple", "Tomato"])

plt.colorbar()

plt.show()

print(
    classification_report(
        y_test,
        y_pred,
        target_names=["Apple", "Tomato"]
    )
)

from google.colab import files

uploaded_image = files.upload()

filename = list(uploaded_image.keys())[0]

img = Image.open(filename).convert("RGB")
img = img.resize((IMG_SIZE, IMG_SIZE))

img_array = np.array(img)
img_array = img_array.flatten()
img_array = img_array / 255.0

prediction = model.predict([img_array])[0]

probability = model.predict_proba([img_array])[0]

if prediction == 0:
    print("🍎 Prediction: APPLE")
    print("Confidence:", probability[0] * 100, "%")
else:
    print("🍅 Prediction: TOMATO")
    print("Confidence:", probability[1] * 100, "%")

print("Apple = 0")
print("Tomato = 1")

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

print("\nActual test labels:")
print(np.bincount(y_test))

print("\nPredicted test labels:")
print(np.bincount(y_pred))

print("Accuracy:", accuracy_score(y_test, y_pred))

apple_test = os.listdir(apple_path)[10]

img = Image.open(
    os.path.join(apple_path, apple_test)
).convert("RGB")

img = img.resize((IMG_SIZE, IMG_SIZE))

plt.imshow(img)
plt.axis("off")
plt.show()

img_array = np.array(img)
img_array = img_array.flatten()
img_array = img_array / 255.0

prediction = model.predict([img_array])[0]
probability = model.predict_proba([img_array])[0]

print("Prediction:", prediction)
print("Probabilities:", probability)

if prediction == 0:
    print("🍎 APPLE")
else:
    print("🍅 TOMATO")