# -*- coding: utf-8 -*-
"""Ml.logistics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FTRNj3KMZq7r1h_QDmFQJjgqpaXjDN6w
"""

import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

"""Prepare dataset , hours studied"""

X = np.array([[1],[2],[2.5],[2.9],[3.7],[5],[5.6],[5.9] ,[7], [8],[4.7], [10] ])

print(type(X))

"""Pass =1 , Fail =0"""

y = np.array([0,0,0,0,1,1,1,1,1,1,1,1])

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state =11)

X_train

y_train

X_test

y_test

m = LogisticRegression()

m.fit(X_train, y_train)

y_pred = m.predict(X_test)
print(y_pred)

a = accuracy_score(y_pred,y_test)
print(a)

Hours = np.array([[2.2]])

Output = m.predict(Hours)

print(Output)

probability = m.predict_proba(X_test)

if probability[0][1] >= 3:
  print("Pass")
else:
  print("Fail")

print("probability of fail", probability[0][0])
print("probability of pass", probability[0][1])

